/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_signal_argon2_Argon2Native */

#ifndef _Included_org_signal_argon2_Argon2Native
#define _Included_org_signal_argon2_Argon2Native
#ifdef __cplusplus
extern "C" {
#endif
#undef org_signal_argon2_Argon2Native_OK
#define org_signal_argon2_Argon2Native_OK 0L
/*
 * Class:     org_signal_argon2_Argon2Native
 * Method:    hash
 * Signature: (III[B[B[BLjava/lang/StringBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_signal_argon2_Argon2Native_hash
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jbyteArray, jbyteArray, jobject, jint, jint);

/*
 * Class:     org_signal_argon2_Argon2Native
 * Method:    verify
 * Signature: (Ljava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_org_signal_argon2_Argon2Native_verify
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     org_signal_argon2_Argon2Native
 * Method:    resultToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_signal_argon2_Argon2Native_resultToString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
